# Generated by Django 5.0.1 on 2024-02-03 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Enter a valid Phone number. Don't Add +91 or 0", regex='^\\+?1?\\d{10,11}$')]),
        ),
    ]
