# Generated by Django 5.0.1 on 2024-02-29 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Name', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=15)),
                ('Pincode', models.CharField(max_length=6)),
                ('State', models.CharField(max_length=20)),
                ('Street_Address', models.CharField(max_length=50)),
                ('Landmark', models.CharField(blank=True, max_length=75)),
            ],
        ),
    ]
