# Generated by Django 5.0.1 on 2024-02-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passivetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Passive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('para1', models.TextField()),
                ('image1', models.ImageField(upload_to='resistor_images/')),
                ('para2', models.TextField()),
                ('h2', models.CharField(max_length=50)),
                ('para3', models.TextField()),
                ('h3', models.CharField(max_length=50)),
                ('para4', models.TextField()),
                ('image2', models.ImageField(upload_to='resistor_images/')),
                ('resistor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Components.passivetype')),
            ],
        ),
    ]
