# Generated by Django 5.0.1 on 2024-02-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0002_remove_passive_resistor_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passivetype',
        ),
        migrations.RemoveField(
            model_name='passive',
            name='h3',
        ),
        migrations.RemoveField(
            model_name='passive',
            name='para4',
        ),
        migrations.AddField(
            model_name='passive',
            name='background_image',
            field=models.ImageField(default=1, upload_to='Passive/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passive',
            name='image1',
            field=models.ImageField(upload_to='Passive/'),
        ),
        migrations.AlterField(
            model_name='passive',
            name='image2',
            field=models.ImageField(upload_to='Passive/'),
        ),
    ]
