# Generated by Django 5.0.1 on 2024-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0004_passive_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passive',
            name='type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
