# Generated by Django 5.0.1 on 2024-02-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0005_alter_passive_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
                ('heading', models.CharField(max_length=100)),
                ('background_image', models.ImageField(upload_to='Active/')),
                ('para1', models.TextField()),
                ('image1', models.ImageField(upload_to='Active/')),
                ('h2', models.CharField(max_length=50)),
                ('para2', models.TextField()),
                ('image2', models.ImageField(upload_to='Active/')),
                ('para3', models.TextField()),
                ('h3', models.CharField(max_length=50)),
                ('para4', models.TextField()),
                ('image3', models.ImageField(upload_to='Active/')),
            ],
        ),
    ]
