# Generated by Django 5.0.1 on 2024-02-06 09:47

import Components.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0009_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive'), ('ElectroMechanical', 'ElectroMechanical'), ('Display', 'Display'), ('Sensor', 'Sensor')], max_length=20)),
                ('Type', models.CharField(max_length=20, unique=True)),
                ('heading', models.CharField(max_length=100)),
                ('content1', models.TextField(blank=True)),
                ('content2', models.TextField(blank=True)),
                ('content3', models.TextField(blank=True)),
                ('content4', models.TextField(blank=True)),
                ('content5', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, upload_to=Components.models.upload_path)),
                ('image1', models.ImageField(blank=True, upload_to=Components.models.upload_path)),
                ('image2', models.ImageField(blank=True, upload_to=Components.models.upload_path)),
                ('image3', models.ImageField(blank=True, upload_to=Components.models.upload_path)),
                ('image4', models.ImageField(blank=True, upload_to=Components.models.upload_path)),
                ('image5', models.ImageField(blank=True, upload_to=Components.models.upload_path)),
            ],
        ),
    ]
