# Generated by Django 5.0.1 on 2024-02-06 09:51

from django.db import migrations

def copy_passive_data_to_component(apps, schema_editor):
    Passive = apps.get_model('Components', 'Passive')
    Component = apps.get_model('Components', 'Component')
    
    for passive_obj in Passive.objects.all():
        Component.objects.create(
            Category='Passive',
            Type=passive_obj.type,
            heading=passive_obj.heading,
            content1=passive_obj.h2,
            content2=passive_obj.para1,
            content3=passive_obj.para2,
            content4=passive_obj.para3,
            background_image=passive_obj.background_image,
            image1=passive_obj.image1,
            image2=passive_obj.image2
            # Add other fields as needed
        )

class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0010_component'),
    ]
    operations = [
        migrations.RunPython(copy_passive_data_to_component),
    ]
