# Generated by Django 5.0.1 on 2024-02-06 09:59

from django.db import migrations

def copy_active_data_to_component(apps, schema_editor):
    Active = apps.get_model('Components', 'Active')
    Component = apps.get_model('Components', 'Component')
    
    for Active_obj in Active.objects.all():
        Component.objects.create(
            Category='Active',
            Type=Active_obj.type,
            heading=Active_obj.heading,
            content1=Active_obj.h2,
            content2=Active_obj.para1,
            content3=Active_obj.para2,
            content4=Active_obj.para3,
            content5=Active_obj.h3+Active_obj.para4,
            background_image=Active_obj.background_image,
            image1=Active_obj.image1,
            image2=Active_obj.image2,
            image3=Active_obj.image3,
            # Add other fields as needed
        )
class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0011_auto_20240206_0951'),
    ]

    operations = [
        migrations.RunPython(copy_active_data_to_component),
    ]