# Generated by Django 5.0.1 on 2024-02-06 10:05

from django.db import migrations
def copy_sensor_data_to_component(apps, schema_editor):
    Sensor = apps.get_model('Components', 'Sensor')
    Component = apps.get_model('Components', 'Component')
    
    for Sensor_obj in Sensor.objects.all():
        Component.objects.create(
            Category='Sensor',
            Type=Sensor_obj.type,
            heading=Sensor_obj.heading,
            content1=Sensor_obj.content1,
            content2=Sensor_obj.content2,
            content3=Sensor_obj.content3,
            content4=Sensor_obj.content4,
            content5=Sensor_obj.content5,
            background_image=Sensor_obj.background_image,
            image1=Sensor_obj.image1,
            image2=Sensor_obj.image2,
            image3=Sensor_obj.image3,
            image4=Sensor_obj.image4,
            image5=Sensor_obj.image5,
            # Add other fields as needed
        )

def copy_electro_data_to_component(apps, schema_editor):
    Electromechanical = apps.get_model('Components', 'Electromechanical')
    Component = apps.get_model('Components', 'Component')
    
    for Electromechanical_obj in Electromechanical.objects.all():
        Component.objects.create(
            Category='ElectroMechanical',
            Type=Electromechanical_obj.type,
            heading=Electromechanical_obj.heading,
            content1=Electromechanical_obj.content1,
            content2=Electromechanical_obj.content2,
            content3=Electromechanical_obj.content3,
            content4=Electromechanical_obj.content4,
            content5=Electromechanical_obj.content5,
            background_image=Electromechanical_obj.background_image,
            image1=Electromechanical_obj.image1,
            image2=Electromechanical_obj.image2,
            image3=Electromechanical_obj.image3,
            image4=Electromechanical_obj.image4,
            image5=Electromechanical_obj.image5,
            # Add other fields as needed
        )

def copy_display_data_to_component(apps, schema_editor):
    Display = apps.get_model('Components', 'Display')
    Component = apps.get_model('Components', 'Component')
    
    for Display_obj in Display.objects.all():
        Component.objects.create(
            Category='Display',
            Type=Display_obj.type,
            heading=Display_obj.heading,
            content1=Display_obj.content1,
            content2=Display_obj.content2,
            content3=Display_obj.content3,
            content4=Display_obj.content4,
            content5=Display_obj.content5,
            background_image=Display_obj.background_image,
            image1=Display_obj.image1,
            image2=Display_obj.image2,
            image3=Display_obj.image3,
            image4=Display_obj.image4,
            image5=Display_obj.image5,
            # Add other fields as needed
        )



class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0012_auto_20240206_0959'),
    ]

    operations = [
        migrations.RunPython(copy_electro_data_to_component),
        migrations.RunPython(copy_display_data_to_component),
        migrations.RunPython(copy_sensor_data_to_component),
    ]
