# Generated by Django 5.0.1 on 2024-02-07 11:49

import Components.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0013_auto_20240206_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('Bundle_set', models.PositiveIntegerField(default=1)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heading', models.CharField(max_length=100)),
                ('P_image', models.ImageField(blank=True, upload_to=Components.models.upload_path_products)),
                ('content1', models.TextField(blank=True)),
                ('content2', models.TextField(blank=True)),
                ('content3', models.TextField(blank=True)),
                ('content4', models.TextField(blank=True)),
                ('content5', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, upload_to=Components.models.upload_path_products)),
                ('image1', models.ImageField(blank=True, upload_to=Components.models.upload_path_products)),
                ('image2', models.ImageField(blank=True, upload_to=Components.models.upload_path_products)),
                ('image3', models.ImageField(blank=True, upload_to=Components.models.upload_path_products)),
                ('image4', models.ImageField(blank=True, upload_to=Components.models.upload_path_products)),
                ('image5', models.ImageField(blank=True, upload_to=Components.models.upload_path_products)),
            ],
        ),
    ]
