# Generated by Django 5.0.1 on 2024-02-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0014_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('Resistor', 'Resistor'), ('Capacitor', 'Capacitor'), ('Inductor', 'Inductor'), ('Transformer', 'Transformer'), ('Transistor', 'Transistor'), ('IC', 'IC'), ('Thyristor', 'Thyristor'), ('Diode', 'Diode'), ('Amplifier', 'Amplifier'), ('Relay', 'Relay'), ('Switch', 'Switch'), ('Motor', 'Motor'), ('Solenoid', 'Solenoid'), ('Actuator', 'Actuator'), ('LCD', 'LCD'), ('LED', 'LED'), ('OLED', 'OLED'), ('TFT', 'TFT'), ('TouchScreen', 'TouchScreen'), ('Temperature', 'Temperature'), ('Pressure', 'Pressure'), ('Motion', 'Motion'), ('Light', 'Light'), ('Gas', 'Gas')], max_length=20, null=True),
        ),
    ]
