# Generated by Django 5.0.1 on 2024-02-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0015_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active',
        ),
        migrations.DeleteModel(
            name='Display',
        ),
        migrations.DeleteModel(
            name='Electromechanical',
        ),
        migrations.DeleteModel(
            name='Passive',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
